"""Write a redacted copy of the FYP proposal for the public repository.

docs/proposal/ is git-ignored because it holds three students' phone numbers.
That is the right call for the form itself, but it also means the repository has
no record of what was submitted, so a correction after the fact has nothing to
compare against. This writes a copy with the personal contact details removed and
everything else intact.

Scope, and why it is this narrow:

  Redacted   the three phone numbers. Personal contact data with no equivalent
             public record, and the only reason docs/proposal/ is ignored.

  Kept       the student names, the registration numbers, the section, the
             supervisor and the FYP coordinator. All of these are already public
             in thesis/00-front-matter.md, which is tracked on a public remote
             and names all three students with their registration numbers and
             Dr. Amna Ikram as supervisor. Redacting them here would protect
             nothing while making the submitted record less useful as a
             comparison baseline.

Run it after every edit to the source:

    python scripts/proposal/make_redacted_copy.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "docs" / "proposal" / "XIII-A_Proposal.md"
TARGET = ROOT / "docs" / "fyp" / "XIII-A_Proposal.redacted.md"

#: The letterhead is copied rather than referenced. docs/proposal/ is ignored, so
#: a relative path back into it renders on this machine and 404s on GitHub, which
#: would leave the published copy without a crest. The university emblem carries
#: no personal data.
LOGO_SRC = ROOT / "docs" / "proposal" / "assets" / "nutech-logo.png"
LOGO_DST = ROOT / "docs" / "fyp" / "assets" / "nutech-logo.png"

#: E.164-ish, tolerant of spacing: +92 319 5976571, +923195976571, +92-319-5976571
PHONE = re.compile(r"\+\d{2}[\s-]?\d{3}[\s-]?\d{7}")

MASK = "[withheld]"

BANNER = """<!--
REDACTED COPY. Generated by scripts/proposal/make_redacted_copy.py -- do not edit
by hand, and do not add contact details here.

The three student phone numbers in the group details table have been replaced
with {mask}. They are the only personal data withheld: the student names,
registration numbers, section, supervisor and FYP coordinator are already public
in thesis/00-front-matter.md on this public remote, so redacting them here would
protect nothing.

The unredacted original is not in git. It lives at docs/proposal/XIII-A_Proposal.md.
-->

"""


def main(argv: list[str]) -> int:
    if not SOURCE.is_file():
        print(f"no source proposal at {SOURCE}")
        return 2

    text = SOURCE.read_text(encoding="utf-8")
    found = PHONE.findall(text)
    redacted = PHONE.sub(MASK, text)

    if not found:
        print("no phone numbers found; check the pattern before publishing")
        return 1

    # The frontmatter is metadata for the renderer, so the banner goes after it
    # rather than before, where it would become a YAML document.
    if redacted.startswith("---"):
        end = redacted.find("\n---", 3)
        if end != -1:
            cut = redacted.index("\n", end + 1)
            head, tail = redacted[:cut], redacted[cut:]
            redacted = f"{head}\n\n{BANNER.format(mask=MASK)}{tail.lstrip()}"
        else:
            redacted = f"{BANNER.format(mask=MASK)}{redacted}"
    else:
        redacted = f"{BANNER.format(mask=MASK)}{redacted}"

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    if LOGO_SRC.is_file():
        LOGO_DST.parent.mkdir(parents=True, exist_ok=True)
        LOGO_DST.write_bytes(LOGO_SRC.read_bytes())
        print(f"letterhead copied -> {LOGO_DST.relative_to(ROOT)}")
    else:
        print(f"WARNING no letterhead at {LOGO_SRC}; the published copy will have none")
    TARGET.write_text(redacted, encoding="utf-8")

    print(f"redacted {len(found)} phone number(s) -> {TARGET.relative_to(ROOT)}")
    leftover = PHONE.findall(TARGET.read_text(encoding="utf-8"))
    if leftover:
        print(f"REFUSING: {len(leftover)} phone number(s) survived the redaction")
        return 1
    print("verified: no phone number remains in the output")

    for ref in set(re.findall(r"!\[[^\]]*\]\(([^)]+)\)", TARGET.read_text(encoding="utf-8"))):
        if not (TARGET.parent / ref).is_file():
            print(f"REFUSING: {ref} is referenced but not present next to the copy")
            return 1
    print("verified: every referenced image resolves beside the copy")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
