/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StartRouteImport } from './routes/start'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as RankingsRunIdRouteImport } from './routes/rankings.$runId'
import { Route as PopulationRunIdRouteImport } from './routes/population.$runId'
import { Route as PathsRunIdRouteImport } from './routes/paths.$runId'
import { Route as MetadataRunIdRouteImport } from './routes/metadata.$runId'
import { Route as GraphRunIdRouteImport } from './routes/graph.$runId'
import { Route as ExportRunIdRouteImport } from './routes/export.$runId'
import { Route as DashboardRunIdRouteImport } from './routes/dashboard.$runId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRunIdRoute = RankingsRunIdRouteImport.update({
  id: '/rankings/$runId',
  path: '/rankings/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const PopulationRunIdRoute = PopulationRunIdRouteImport.update({
  id: '/population/$runId',
  path: '/population/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRunIdRoute = PathsRunIdRouteImport.update({
  id: '/paths/$runId',
  path: '/paths/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataRunIdRoute = MetadataRunIdRouteImport.update({
  id: '/metadata/$runId',
  path: '/metadata/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRunIdRoute = GraphRunIdRouteImport.update({
  id: '/graph/$runId',
  path: '/graph/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRunIdRoute = ExportRunIdRouteImport.update({
  id: '/export/$runId',
  path: '/export/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRunIdRoute = DashboardRunIdRouteImport.update({
  id: '/dashboard/$runId',
  path: '/dashboard/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/dashboard/$runId': typeof DashboardRunIdRoute
  '/export/$runId': typeof ExportRunIdRoute
  '/graph/$runId': typeof GraphRunIdRoute
  '/metadata/$runId': typeof MetadataRunIdRoute
  '/paths/$runId': typeof PathsRunIdRoute
  '/population/$runId': typeof PopulationRunIdRoute
  '/rankings/$runId': typeof RankingsRunIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/dashboard/$runId': typeof DashboardRunIdRoute
  '/export/$runId': typeof ExportRunIdRoute
  '/graph/$runId': typeof GraphRunIdRoute
  '/metadata/$runId': typeof MetadataRunIdRoute
  '/paths/$runId': typeof PathsRunIdRoute
  '/population/$runId': typeof PopulationRunIdRoute
  '/rankings/$runId': typeof RankingsRunIdRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/dashboard/$runId': typeof DashboardRunIdRoute
  '/export/$runId': typeof ExportRunIdRoute
  '/graph/$runId': typeof GraphRunIdRoute
  '/metadata/$runId': typeof MetadataRunIdRoute
  '/paths/$runId': typeof PathsRunIdRoute
  '/population/$runId': typeof PopulationRunIdRoute
  '/rankings/$runId': typeof RankingsRunIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/start'
    | '/terms'
    | '/dashboard/$runId'
    | '/export/$runId'
    | '/graph/$runId'
    | '/metadata/$runId'
    | '/paths/$runId'
    | '/population/$runId'
    | '/rankings/$runId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/start'
    | '/terms'
    | '/dashboard/$runId'
    | '/export/$runId'
    | '/graph/$runId'
    | '/metadata/$runId'
    | '/paths/$runId'
    | '/population/$runId'
    | '/rankings/$runId'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/start'
    | '/terms'
    | '/dashboard/$runId'
    | '/export/$runId'
    | '/graph/$runId'
    | '/metadata/$runId'
    | '/paths/$runId'
    | '/population/$runId'
    | '/rankings/$runId'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  DashboardRunIdRoute: typeof DashboardRunIdRoute
  ExportRunIdRoute: typeof ExportRunIdRoute
  GraphRunIdRoute: typeof GraphRunIdRoute
  MetadataRunIdRoute: typeof MetadataRunIdRoute
  PathsRunIdRoute: typeof PathsRunIdRoute
  PopulationRunIdRoute: typeof PopulationRunIdRoute
  RankingsRunIdRoute: typeof RankingsRunIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings/$runId': {
      id: '/rankings/$runId'
      path: '/rankings/$runId'
      fullPath: '/rankings/$runId'
      preLoaderRoute: typeof RankingsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/population/$runId': {
      id: '/population/$runId'
      path: '/population/$runId'
      fullPath: '/population/$runId'
      preLoaderRoute: typeof PopulationRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/$runId': {
      id: '/paths/$runId'
      path: '/paths/$runId'
      fullPath: '/paths/$runId'
      preLoaderRoute: typeof PathsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata/$runId': {
      id: '/metadata/$runId'
      path: '/metadata/$runId'
      fullPath: '/metadata/$runId'
      preLoaderRoute: typeof MetadataRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/$runId': {
      id: '/graph/$runId'
      path: '/graph/$runId'
      fullPath: '/graph/$runId'
      preLoaderRoute: typeof GraphRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export/$runId': {
      id: '/export/$runId'
      path: '/export/$runId'
      fullPath: '/export/$runId'
      preLoaderRoute: typeof ExportRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$runId': {
      id: '/dashboard/$runId'
      path: '/dashboard/$runId'
      fullPath: '/dashboard/$runId'
      preLoaderRoute: typeof DashboardRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  DashboardRunIdRoute: DashboardRunIdRoute,
  ExportRunIdRoute: ExportRunIdRoute,
  GraphRunIdRoute: GraphRunIdRoute,
  MetadataRunIdRoute: MetadataRunIdRoute,
  PathsRunIdRoute: PathsRunIdRoute,
  PopulationRunIdRoute: PopulationRunIdRoute,
  RankingsRunIdRoute: RankingsRunIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
