"""Correct Anas Zafar's registration number across the repository.

The number was wrong in four hand-maintained files, which means the error had
reached the thesis front matter, the README, the presentation slides and the
proposal. Two further files carry it but are build products and are not edited
here:

  thesis/CiteGraph-NLP-Thesis.md        regenerated by scripts/build_thesis.py
  docs/fyp/XIII-A_Proposal.redacted.md  regenerated by
                                        scripts/proposal/make_redacted_copy.py

The thesis .docx and .pdf are rebuilt from the assembled markdown afterwards, and
they are where the error was most costly: those are the artefacts a supervisor
reads.

Run from the repository root, then rebuild:

    python scripts/fix_reg_number.py
    python scripts/build_thesis.py
    python scripts/render_thesis.py
    python scripts/render_thesis.py --docx
    python scripts/proposal/make_redacted_copy.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

WRONG = "F22607024"
RIGHT = "F22607025"

#: Hand-maintained only. Generated files are listed so an unexpected hit is
#: reported rather than silently skipped, but never edited.
SOURCES = [
    "README.md",
    "docs/presentation_slides_10.md",
    "thesis/00-front-matter.md",
    "docs/proposal/XIII-A_Proposal.md",
]
GENERATED = [
    "thesis/CiteGraph-NLP-Thesis.md",
    "docs/fyp/XIII-A_Proposal.redacted.md",
]


def main(argv: list[str]) -> int:
    changed = []
    for rel in SOURCES:
        p = ROOT / rel
        if not p.is_file():
            print(f"missing, skipped: {rel}")
            continue
        t = p.read_text(encoding="utf-8")
        n = t.count(WRONG)
        if n == 0:
            print(f"already correct: {rel}")
            continue
        p.write_text(t.replace(WRONG, RIGHT), encoding="utf-8")
        changed.append((rel, n))
        print(f"fixed {n} in {rel}")

    if not changed:
        print("nothing to correct")

    print("\ngenerated files still holding the old number until rebuilt:")
    for rel in GENERATED:
        p = ROOT / rel
        if p.is_file() and WRONG in p.read_text(encoding="utf-8", errors="replace"):
            print(f"  {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
